FROM wiiuenv/devkitppc:20220724

COPY --from=wiiuenv/libmocha:20220726 /artifacts $DEVKITPRO

WORKDIR tmp_build
COPY . .
RUN make clean && make wiiu-release && mkdir -p /artifacts/wut/usr && mkdir -p /artifacts/wut/usr/lib && cp lib/wiiu/libntfs.a /artifacts/wut/usr/lib && cp -r include /artifacts/wut/usr
WORKDIR /artifacts

FROM scratch
COPY --from=0 /artifacts /artifacts